# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71711b093d2abf8d873db0f6ca5a2750e48379a342073cb59d38e5820c5e1a02919b5f50ebe2eb2a0432ea654cb550037b170853b6750bf29b70426a0cb43e9d

test:
  secret_key_base: 97f99b73f5682c9d28d392bfe219774740f44cfd827bef72513a7b1c55504d8f4aa56742b5dd1f914c60a3e62ae84610e533641ae44e169749094615c750c1c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
